First-Peoples-Cultural-Council/fv-web-ui

app/assets/javascripts/views/AppFrontController.js

Updated an IF statement that may be preventing users from being redirected upon Signing In. This is difficult to properly test without a local Nuxeo instance.

FV-4: Updated if statement to forward user after successful login.

---

app/assets/javascripts/common/ProviderHelpers.js
app/assets/javascripts/views/pages/explore/dialect/learn/phrases/index.js
app/assets/javascripts/views/pages/explore/dialect/learn/words/index.js

- Investigated Kids views for words and phrases.
- Implemented Kids views for words and phrases when viewing on mobile device while maintaining expected post count.
- Updated ProviderHelpers code style by replacing one liner shorthand IF statements with curly braces.
- Investigated fixing Loading Icon on Phrases page, and failed. Created new Issue for this.

FV-119: Mobile display of word and Phrase on iPhone

---

frontend/app/assets/javascripts/common/ProviderHelpers.js
frontend/app/assets/javascripts/common/__tests__/ProviderHelpers.js

Includes jest test but this branch isn't currently setup to support jest tests (it's supported in the `jest-integration` branch).
FROM:
```
getDialectPathFromURLArray: function(url) {
return decodeURI(url.slice(1, 7).join('/'))
},
```
TO:
```
/*
getDialectPathFromURLArray(urlArray)
Extracts dialect path from url array.
Returns null if not found
*/
function getDialectPathFromURLArray(urlArray) {
const index = urlArray.findIndex((el) => {
return el.match(/^FV$/)
})
if (index !== -1) {
const _url = urlArray.slice(index, index + 5)
return decodeURI(`/${_url.join('/')}`)
}
return null
}
```
Note: `ProviderHelpers.js` has been reorganized to have the fns() outside of the exported object

Fixing ProviderHelpers.js > getDialectPathFromURLArray()

---

frontend/README.md
frontend/app/assets/javascripts/views/pages/explore/dialect/ExploreDialectEdit/__cypress__/LangAdminPortal-Inline.js
frontend/app/assets/javascripts/views/pages/explore/dialect/ExploreDialectEdit/__cypress__/LangAdminPortal.js
frontend/app/assets/javascripts/views/pages/explore/dialect/Phrasebook/__cypress__/PhrasebookCreate.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/phrases/__cypress__/LangAdminCreateDelete-Phrase.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/phrases/__cypress__/LangAdminViewEdit-Phrase.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/phrases/__cypress__/MemberView-Phrase.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/phrases/__cypress__/RecApprovalCreateDelete-Phrase.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/phrases/__cypress__/RecorderCreate-Phrase.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/songs-stories/__cypress__/LangAdminCreateDelete-Song.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/songs-stories/__cypress__/LangAdminCreateDelete-Story.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/songs-stories/__cypress__/RecApprovalCreateDelete-Song.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/songs-stories/__cypress__/RecApprovalCreateDelete-Story.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/songs-stories/__cypress__/RecorderCreate-Song.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/songs-stories/__cypress__/RecorderCreate-Story.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/words/__cypress__/LangAdminCreateDelete-Word.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/words/__cypress__/LangAdminViewEdit-Word.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/words/__cypress__/MemberVisibility-Word.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/words/__cypress__/RecApprovalCreateDelete-Word.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/words/__cypress__/RecorderCreate-Word.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/words/__cypress__/RecorderEnable-Word.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/words/__cypress__/RecorderMediaTrace-Word.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/words/__cypress__/RecorderPublishUnpublish-Word.js
frontend/app/assets/javascripts/views/pages/explore/dialect/reports/__cypress__/ReportViewFilter.js
frontend/cypress/support/commands.js

These changes will allow Cypress to use a single password from the environment variable CYPRESS_FV_PASSWORD.  The usernames are now hardcoded, reducing the number of environment variables needed to one.

FW-650 Change Cypress tests to use a single password

---

.github/workflows/build.yml

Linux, Windows, and Mac build jobs will run simultaneously on GitHub Actions.
Ensures the project build is working on all three operating systems.

FW-727 Add Windows and Mac build test to CI

---

frontend/app/assets/javascripts/views/components/Navigation/Footer/Footer.css
frontend/app/assets/javascripts/views/components/Navigation/Footer/index.js
frontend/app/assets/javascripts/views/components/Navigation/index.js
frontend/app/assets/javascripts/views/pages/home/index.js

- Added hrefs to FV (Header) and FPCC (Footer) logos
- bypassed intl.searchAndReplace on home page to avoid truncating text block

FW-711-comms-updates

---

frontend/app/assets/javascripts/views/hoc/grid-list/with-pagination.js

JS was receiving the content for the new pages and was passing it in as props but the component wasn't re-rendering.
Think that `shouldComponentUpdate` always returning `false` in `with-pagination.js` was preventing the Kids > Stories from updating the page content. 
Note: It's not clear to me at the moment why this issue was only present in the kids view.
> Use shouldComponentUpdate() to let React know if a component’s output is not affected by the current change in state or props.
...
This method only exists as a performance optimization. Do not rely on it to “prevent” a rendering, as this can lead to bugs.
https://reactjs.org/docs/react-component.html#shouldcomponentupdate

FW-697 kids story paging

---

frontend/app/assets/javascripts/common/UIHelpers.js
frontend/app/assets/javascripts/views/components/Browsing/DictionaryList.css
frontend/app/assets/javascripts/views/components/Browsing/DictionaryList.js
frontend/app/assets/javascripts/views/components/Browsing/DictionaryListSmallScreen.css
frontend/app/assets/javascripts/views/components/DialectFilterList/index.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/base/data-list-view.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/phrases/list-view.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/words/list-view.js
frontend/app/assets/javascripts/views/pages/search/index.js
frontend/app/assets/stylesheets/AlphabetListView.less
frontend/app/assets/stylesheets/DialectFilterList.less
frontend/app/assets/stylesheets/SearchDialect.less
frontend/app/assets/stylesheets/main.less

Removed the 'Compact view' button since more rows can fit in the desktop view. The new 'compact' view is meant to improve design on small screens and not fit in as many entries as possible.
Impacts:
- Phrases & words: small view
- Search: all views

FW-811 Better looking small screen view

---

frontend/index.html

This makes it so that the hidden commit number on the main page now links to the commit on Github.

FW-1052 - Turned hidden commit text into link

---

FVUserRegistration/UpdateModule.sh
FirstVoices-marketplace/UpdateModule.sh
FirstVoicesData/UpdateModule.sh
FirstVoicesDraftEditor/UpdateModule.sh
FirstVoicesEnrichers/UpdateModule.sh
FirstVoicesExport/UpdateModule.sh
FirstVoicesPublisher/UpdateModule.sh
FirstVoicesSecurity/UpdateModule.sh
docker/README.md
docker/UpdateModuleMain.sh
migration-contributions/UpdateModule.sh

Running the update module script with the -skip-tests flag will skip compilation and running of unit tests during a local module docker deploy. 
To run: ```./UpdateModule.sh -skip-tests``` in the root directory of a module.

Add optional -skip-tests flag to UpdateModule scripts

---

Dockerfile
docker/README.md

- Removed `ufraw` library from docker image build since it is not available on Ubuntu 20.04
- Added `ENV DEBIAN_FRONTEND=noninteractive` to address timezone library interaction requirement.
- Added more info to Java install in README

FW-1278 Adjustments to docker container for Ubuntu 20.04

---

FirstVoices-marketplace/src/main/assemble/assembly.xml
FirstVoices-marketplace/src/main/resources/install.xml
FirstVoicesDraftEditor/pom.xml
FirstVoicesPublisher/pom.xml
FirstVoicesPublisher/src/main/java/ca/firstvoices/operations/CheckUnpublishedChanges.java
FirstVoicesPublisher/src/main/java/ca/firstvoices/operations/GetUnpublishedChanges.java
FirstVoicesPublisher/src/main/java/ca/firstvoices/services/UnpublishedChangesService.java
FirstVoicesPublisher/src/main/java/ca/firstvoices/services/UnpublishedChangesServiceImpl.java
FirstVoicesPublisher/src/main/resources/OSGI-INF/extensions/ca.firstvoices.operations.xml
docker/README.md
pom.xml

Notes:
- Document.CheckUnpublishedChanges: Rather than evaluating the version of documents, the service was updated to do a diff, excluding properties and schemas that are not likely to be updated by end-users. We will need to adjust this as we introduce new schemas that are not user facing.
- Document.GetUnpublishedChanges: This is a new end-point that will actually display the diff between the two documents.
This change introduces a new external library (https://javers.org/)

FW-1294: Unpublished changes based on diff

---

frontend/app/assets/javascripts/views/pages/explore/dialect/learn/words/categoriesDataLayer.js

Having a separate data layer for Phrase Books should be considered for later. (Really like how the data layer simplifies these calls!)

FW-1339 - set categories conditionally, fall back to shared if needed

---

FirstVoicesData/src/main/resources/data/schemas/fvlegacy.xsd

This is necessary for importing textual IDs from the Smalgyax archive.

FW-1320 Capture import id in new field to support text

---

frontend/app/assets/javascripts/views/components/DialectFilterList/DialectFilterList.css
frontend/app/assets/javascripts/views/components/DialectFilterList/DialectFilterListData.js
frontend/app/assets/javascripts/views/components/DialectFilterList/DialectFilterListPresentation.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/phrases/index.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/phrases/phrasesFilteredByCategory.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/words/index.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/words/wordsFilteredByCategory.js
frontend/app/assets/stylesheets/main.less

- Extracted Data & Presentation components from branch FW-1234-v2
- Moved .less to co-locate .css
- DialectFilterListData now supports passing in data via the `transformData` prop. Used in combination with the CategoriesDataLayer. When `transformData` exists, DialectFilterListData won't make requests to get the data

FW-1421 Extract changes related to DialectFilterListData from the `FW-1234-v2` branch

---

frontend/cypress/support/commands.js

- Moved logout command from afterEach to beforeEach. A Cypress test could be interrupted and tests that follow may fail since the afterEach logout would not have run - https://docs.cypress.io/guides/references/best-practices.html#Using-after-or-afterEach-hooks
- Removed out of date log messages in beforeEach
- Added some TODO notes to the afterEach wait command (related to video)

Cypress Best Practices

---

FirstVoices-marketplace/pom.xml
FirstVoicesHealthMonitor/pom.xml
FirstVoicesHealthMonitor/src/main/java/ca/firstvoices/probes/NodeStatusServlet.java
FirstVoicesHealthMonitor/src/main/resources/META-INF/MANIFEST.MF
FirstVoicesHealthMonitor/src/main/resources/OSGI-INF/deployment-fragment.xml
FirstVoicesHealthMonitor/src/test/resources/META-INF/MANIFEST.MF
pom.xml

- Added `/nuxeo/nodestatus` servlet, returning a JSON object containing node cluster ID and instance name.
- It is not possible to add detailed information to the `/nuxeo/runningstatus` endpoint, since it permits only pass/fail notifications.
- Recommend this endpoint (and perhaps `/nuxeo/runningstatus`) be guarded by front proxy/balancer

FW-1395 Add node status servlet

---

frontend/app/assets/javascripts/views/pages/explore/dialect/learn/base/index.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/base/toolbar-navigation.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/phrases/index.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/phrases/list-view.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/phrases/phrasesFilteredByCategory.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/words/index.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/words/wordsFilteredByCategory.js

https://firstvoices.atlassian.net/browse/FW-1514
Search: not saving settings on 1st search, subsequent searches work correctly
Cause/Background:
- /learn/words is considered different than /learn/words/10/1
- if you search from /learn/words, the results are shown on /learn/words/10/1
- during that transition the SearchDialect values are reset (cause of error)
Changes:
- updated urls to point to words & phrases with pagination included, eg: `/learn/words/10/1` instead of `/learn/words`
- added a check in `.../learn/phrases/list-view.js` to suppress duplicate requests. Fixes the 'old information is briefly displayed' issue

FW-1514, FW-1501, FW-1502

---

frontend/app/assets/javascripts/common/DataSource/useAudio.js
frontend/app/assets/javascripts/components/AudioMinimal/AudioMinimalContainer.js
frontend/app/assets/javascripts/components/AudioMinimal/AudioMinimalData.js
frontend/app/assets/javascripts/components/AudioMinimal/AudioMinimalPresentation.js
frontend/app/assets/javascripts/components/AudioMinimal/index.js
frontend/app/assets/javascripts/providers/redux/reducers/audio/actionTypes.js
frontend/app/assets/javascripts/providers/redux/reducers/audio/actions.js
frontend/app/assets/javascripts/providers/redux/reducers/audio/index.js
frontend/app/assets/javascripts/providers/redux/reducers/audio/reducer.js
frontend/app/assets/javascripts/providers/redux/reducers/index.js

The PR for `FW-1481-kids-phrases` is a bit too large so I'm pulling out features that can be PRed separately.
Adds new AudioMinimal components (Data, Presentation, Container, DataSource) and related Redux reducer
Features:
- Easy to use, just need a url to the audio: ```<AudioMinimal.Container src={audio} />```
- Plays one file at a time. Stops any in-progress audio before starting new audio
- Stops audio on unmount

AudioMinimal components (Data, Presentation, Container, DataSource) and related Redux reducer

---

FirstVoicesPublisher/src/main/java/ca/firstvoices/nativeorder/listeners/ComputeNativeOrderDialectListener.java

Before this change, if this flag had not been initialized on an alphabet document: “fv-alphabet:update_confusables_required", the customOrderRecompute query would not pick up the alphabet document because of the query.

FW-1667: Update NXQL Query For Custom Order Recompute

---

frontend/app/assets/javascripts/components/WordsList/WordsListData.js
frontend/app/assets/javascripts/views/components/Browsing/DictionaryListSmallScreen.js

- Triggered by accessing deeply nested object that is undefined when on `sections`
- Created a custom template to render State and enabled it over in `getColumns()`

FW-1708 Site crashes on word view w/small screens when on /sections

---

FirstVoicesData/src/main/java/ca/firstvoices/services/CleanupCharactersServiceImpl.java

The .getPropertyValue calls could be non null, but when casted to a string array become a null array. This fix casts the getPropertyValue calls first, then tests if they are null.

Fix possible properties being cast as null arrays

---

FirstVoicesData/src/main/java/ca/firstvoices/listeners/FVDocumentListener.java
FirstVoicesData/src/main/java/ca/firstvoices/services/AddConfusablesService.java
FirstVoicesData/src/main/java/ca/firstvoices/services/AddConfusablesServiceImpl.java
FirstVoicesData/src/main/java/ca/firstvoices/services/CleanupCharactersService.java
FirstVoicesData/src/main/java/ca/firstvoices/services/CleanupCharactersServiceImpl.java
FirstVoicesData/src/test/java/ca/firstvoices/services/AddConfusablesServiceImplTest.java
FirstVoicesData/src/test/java/ca/firstvoices/services/CleanupCharactersServiceImplTest.java

- validateCharacters method can now handle documents with null upper case values
- validateCharacter method now takes a document as a parameter for clarity
- FVCharacterInvalid exceptions now display the invalid characters or hash maps
- Adding confusables now skips confusables that are already a part of a dialect's alphabet
- Added some documentation comments for clarity

FW-1739 Fix addConfusables failing character validation

---

FirstVoicesCoreTests/src/main/java/ca/firstvoices/tests/mocks/services/MockDialectServiceImpl.java

Initially the order of the first letter in the alphabet was set to zero causing errors. It is now set to 1.

FW-1792: Fix order compute error by making order non zero

---

FirstVoicesSecurity/pom.xml
FirstVoicesSimplifiedAPI/dependency-reduced-pom.xml

FirstVoicesSimplifiedAPI -> dependency-reduced-pom.xml was excluding gson.jar from the built ZIP file - which was necessary to be included for the javers library.

Fix pom.xml issues

---

frontend/app/assets/javascripts/common/DataSource/useDashboard.js
frontend/app/assets/javascripts/components/DashboardDetailTasks/DashboardDetailTasksData.js
frontend/app/assets/javascripts/components/WidgetTasks/WidgetTasksData.js

- Disabled sort on `Entry title` column since it's a deeply nested prop that we can't sort against (at the moment)
- Dashboard Detail > Table view updates url on sort
- `useDashboard` update to set the correct data prop name when sorting

FW-1624 Sorting on widget & detail view

---

FirstVoicesCharacters/src/main/java/ca/firstvoices/characters/workers/AddConfusablesWorker.java

This process needs to be manual so that a user/superadmin can change the confusables before they are cleaned.

FW-1875 - Do not run Clean.Confusables after add confusables

---

FirstVoicesCoreIO/src/main/java/ca/firstvoices/core/io/utils/DialectUtils.java
FirstVoicesCoreIO/src/main/java/ca/firstvoices/core/io/utils/DocumentUtils.java
FirstVoicesCoreIO/src/test/java/ca/firstvoices/core/io/utils/DialectUtilsTest.java
FirstVoicesCoreTests/src/test/resources/test-data/test-language.yaml
FirstVoicesData/src/main/java/ca/firstvoices/data/schemas/DialectTypesConstants.java
FirstVoicesMaintenance/src/main/java/ca/firstvoices/maintenance/listeners/PostCommitCleanupListener.java
FirstVoicesMaintenance/src/main/resources/OSGI-INF/maintenance/fv-maintenance-contrib.xml
FirstVoicesMaintenance/src/test/java/ca/firstvoices/maintenance/listeners/PostCommitCleanupListenerTest.java
FirstVoicesRESTPageProviders/src/main/resources/OSGI-INF/extensions/ca.firstvoices.pageproviders.tasks.xml

Made some slight changes to FVCore, FVData.
Opted to put this logic in FVMaintenance so that we can use this for future post commit, async cleanup events that need to happen after a doc is committed. Alternatively this could like in an FVTasks package if we create one.

FW-1850 - remove tasks after changes to doc by non admins

---

frontend/app/assets/javascripts/views/hoc/view/with-form.js

Edit form was not saving empty fields, so for example, if a user added pronunciation to a word, they could subsequently update the pronunciation but they couldn't delete it entirely.
NB: `getValue()` on tcomb-form is returning `null` values for string fields that are submitted as empty
Removed `null` filtering logic for non-list form values in _onRequestSaveForm function

FW-1896 Bug fix - not saving emptied form fields

---

FirstVoicesCoreIO/src/main/resources/OSGI-INF/ca.firstvoices.notifications.xml
FirstVoicesCoreIO/src/main/resources/data/templates/changesRequested.ftl

Extracting from comment due to bug with CurrentUser
(see note here: https://doc.nuxeo.com/studio/available-variables-in-email-templates/ -> `${CurrentUser} is not correctly working for now in FTL templates. However, if your email template is sent in the context of an automation chain or script, it is possible to use a workaround by defining its value in a context variable`)

FW-1917 - Use actual user's name in email

---

FirstVoicesMaintenance/src/main/java/ca/firstvoices/maintenance/listeners/ExecuteRequiredJobsListener.java

Should solve issues with log files reporting "cannot find operation with input type void" when multiple required jobs are present.

FW-2002 - create new operation context within loop

---

FirstVoicesCoreIO/src/test/java/ca/firstvoices/core/io/utils/DocumentUtilsTest.java
FirstVoicesData/src/main/java/ca/firstvoices/data/schemas/DomainTypesConstants.java
FirstVoicesMaintenance/src/main/java/ca/firstvoices/maintenance/listeners/ExecuteRequiredJobsListener.java
FirstVoicesPublisher/src/main/java/ca/firstvoices/publisher/listeners/ProxyPublisherListener.java
FirstVoicesPublisher/src/main/java/ca/firstvoices/publisher/services/FirstVoicesPublisherServiceImpl.java
FirstVoicesPublisher/src/test/java/ca/firstvoices/services/PublisherServiceTest.java

Issues resolved:
- Listener was triggering for proxies, as well as workspaces (wrong condition in ProxyPublisherListener), although it most likely did not affect functionality, it would have produced some error in log files
- Dialects can reference shared links (from SharedData) in Keyboards/language resources - this was the main reason for publishing not working in Production, which we didn't catch in Dev/Preprod
- Optimization (and possible solution for things stuck in Republish): the republish end-point will always explicitly set the document to publish bypassing the lifecycle service, and thus not triggering an additional event.

FW-2001 - Publishing fixes

---

modules/api/firstvoices-rest-api/src/main/java/org/nuxeo/ecm/restapi/server/jaxrs/firstvoices/SitesObject.java
modules/common/firstvoices-data/src/main/resources/OSGI-INF/dialect/dialect-contrib.xml
modules/common/firstvoices-data/src/main/resources/data/schemas/fvmedia.xsd
modules/common/firstvoices-data/src/main/resources/data/schemas/fvpage.xsd

FW-2015 - Remove default="false" from fvm:child_focused. Does not seem to have any side effects. Since we use this schema on proxies, and the system seems to attempt to set `false` on update, publishing results in a `cannot set property on proxy` error. See also https://jira.nuxeo.com/browse/NXP-19466
FW-2070 - Ensure Enable, Disable, and RevertToNew apply to children when changing a dialect (caused issues with members not seeing their dialect)
FW-2063 - Workspaces query does not need language family title (explore language). Caused issues by non-super admins trying to access the language object which they do not have permission for.

FW-2015, FW-2070, FW-2063 - various explore language / state bugs

---

frontend/app/common/locale/locale.en.json
frontend/app/components/Register/index.js
frontend/app_v2/index.html
frontend/cypress_CI.json

- Allow retries in Cypress (to allow for flaky tests)
- Fix label that was failing Cypress test
- Other changes to register.js are husky recommendations
- Added viewport meta tag for v2

FW-1808 - Fix registration test; allow retries
