app/assets/javascripts/app.js
app/assets/javascripts/views/components/Document/DocumentListView/index.js
app/assets/javascripts/views/components/Document/view.js
app/assets/javascripts/views/components/Editor/AlloyEditorComponent.js
app/assets/javascripts/views/pages/explore/dialect/gallery/index.js
app/assets/javascripts/views/pages/explore/dialect/learn/phrases/view.js
app/assets/javascripts/views/pages/explore/dialect/learn/words/view.js
gulpfile.js/config/webpack.js
gulpfile.js/tasks/webpack-dev-server.js
package.json
yarn.lock

Upgraded Webpack to a stable version (2.2.1), 
Ran into a few issues with alloyeditor and Webpack parsing it.
So I removed parsing of alloyeditor and exposed React as a global variable.

upgraded webpack 2.2.1

---

app/assets/javascripts/views/pages/explore/dialect/header.js
app/assets/javascripts/views/pages/home/index.js

Centered portal homepage background

Feature fv-96

---

app/assets/javascripts/views/pages/explore/dialect/media/edit.js

• Updated Edit Media Form to redirect to the Language Media Page upon successful Save.

FV-98: Editing New Media in Media Browser should redirect after saving.

---

app/assets/javascripts/views/pages/intro.js

• Added a button that links to the First Voices Legacy website on the new First Voices site's Splash page.

FV-137: Link to legacy.firstvoices.com

---

nuxeo-addons/FVUserRegistration/src/test/java/resources/META-INF/MANIFEST.MF
nuxeo-addons/FVUserRegistration/src/test/java/resources/OSGI-INF/extensions/fake-directory-sql-contrib.xml
nuxeo-addons/FVUserRegistration/src/test/java/resources/OSGI-INF/extensions/fake-load-action.xml
nuxeo-addons/FVUserRegistration/src/test/java/resources/OSGI-INF/extensions/fake-load-es-provider.xml
nuxeo-addons/FirstVoicesEnrichers/src/main/java/ca/firstvoices/nuxeo/enrichers/ParentDocEnricher.java
nuxeo-addons/FirstVoicesEnrichers/src/main/java/ca/firstvoices/nuxeo/operations/DocumentEnrichedQuery.java
nuxeo-addons/FirstVoicesEnrichers/src/main/java/ca/firstvoices/nuxeo/operations/ListDialects.java
nuxeo-addons/FirstVoicesEnrichers/src/main/resources/OSGI-INF/extensions/ca.firstvoices.enrichers.operations.xml
nuxeo-addons/FirstVoicesEnrichers/src/test/java/ca.firstvoices/ListDialectsTest.java
nuxeo-addons/FirstVoicesEnrichers/src/test/java/ca.firstvoices/TestEnricherUtils.java
nuxeo-addons/FirstVoicesEnrichers/src/test/resources/META-INF/MANIFEST.MF
nuxeo-addons/FirstVoicesExport/src/test/resources/META-INF/MANIFEST.MF

Utility operation to list dialects.

V2.2.0 list dialects

---

frontend/app/assets/javascripts/views/components/Editor/SelectMediaComponent.js
frontend/app/assets/javascripts/views/hoc/grid-list/with-filter.js

https://trello.com/c/6mZuHt6Z/696-edit-gallery-filter-state-clears-when-results-display

Trello #696: `Edit gallery -- FILTER state clears when results display.`

---

frontend/app/assets/javascripts/views/pages/explore/dialect/kids.js

It was missing an import: `import NavigationHelpers from 'common/NavigationHelpers'`
Should also fix ER-32

Fixes ER-31: Kids Portal page never loads

---

frontend/app/assets/javascripts/models/schemas/fields.js
frontend/app/assets/javascripts/models/schemas/options.js
frontend/app/assets/javascripts/views/components/Editor/DialectList.js
frontend/app/assets/javascripts/views/components/Editor/DirectoryList.js
frontend/app/assets/javascripts/views/components/Editor/fields/select.js
frontend/app/assets/javascripts/views/pages/explore/dialect/create/Word/validation.js

- Updated Create WOrd form so that part of speech defaults to "Please Select:" and is an optional entry.
- Added a "placeholder" boolean prop to "Directory list", if true will add a placeholder to the field.
- Updated field.js email verification to pass  Husky

Create Word Form Part of speech optional

---

frontend/app/assets/javascripts/locale/locale.en.json
frontend/app/assets/javascripts/views/pages/explore/dialect/Phrasebooks/index.js
frontend/app/assets/javascripts/views/pages/explore/dialect/Recorders/index.js
frontend/app/assets/javascripts/views/pages/explore/dialect/contributors/Contributors.css
frontend/app/assets/javascripts/views/pages/explore/dialect/contributors/index.js
frontend/app/assets/javascripts/views/pages/explore/dialect/page-toolbar.js
frontend/app/assets/stylesheets/main.less

- Browse buttons added to the Dialect page's dropdown menu (that has Media Browser in it)
- Create buttons added to the top of the browse pages

FW-170 Adding links to new Phrase book, Recorder, & Contributor pages

---

frontend/app/assets/javascripts/views/components/Browsing/MetadataList.css
frontend/app/assets/javascripts/views/components/Browsing/metadata-list.js
frontend/app/assets/javascripts/views/components/Editor/Preview.js
frontend/app/assets/javascripts/views/components/Editor/PreviewMetaDataContributor.css
frontend/app/assets/javascripts/views/components/Editor/PreviewMetaDataContributor.js
frontend/app/assets/javascripts/views/pages/explore/dialect/media/view.js

https://firstvoices.atlassian.net/browse/FW-299

FW-299 Media Detail page is broken for most media types

---

frontend/app/assets/javascripts/configuration/routes.js
frontend/app/assets/javascripts/views/pages/explore/dialect/play/index.js

Opening a PR since it involves a url change from:
.../play/hangman
to:
.../play/parachute

FW-274 Games: Parachute is called 'Hangman' in breadcrumb and has 'hangman' in url

---

frontend/app/assets/javascripts/views/pages/explore/dialect/ExploreDialectEdit/__cypress__/LangAdminPortal-Inline.js
frontend/app/assets/javascripts/views/pages/explore/dialect/ExploreDialectEdit/__cypress__/LangAdminPortal.js
frontend/app/assets/javascripts/views/pages/explore/dialect/Phrasebook/__cypress__/PhrasebookCreate.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/phrases/__cypress__/LangAdminCreateDelete-Phrase.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/phrases/__cypress__/LangAdminViewEdit-Phrase.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/phrases/__cypress__/MemberView-Phrase.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/phrases/__cypress__/RecApprovalCreateDelete-Phrase.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/phrases/__cypress__/RecorderCreate-Phrase.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/songs-stories/__cypress__/LangAdminCreateDelete-Song.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/songs-stories/__cypress__/LangAdminCreateDelete-Story.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/songs-stories/__cypress__/RecApprovalCreateDelete-Song.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/songs-stories/__cypress__/RecApprovalCreateDelete-Story.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/songs-stories/__cypress__/RecorderCreate-Song.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/songs-stories/__cypress__/RecorderCreate-Story.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/words/__cypress__/LangAdminCreateDelete-Word.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/words/__cypress__/LangAdminViewEdit-Word.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/words/__cypress__/MemberVisibility-Word.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/words/__cypress__/RecApprovalCreateDelete-Word.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/words/__cypress__/RecorderCreate-Word.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/words/__cypress__/RecorderEnable-Word.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/words/__cypress__/RecorderMediaTrace-Word.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/words/__cypress__/RecorderPublishUnpublish-Word.js
frontend/app/assets/javascripts/views/pages/explore/dialect/reports/__cypress__/ReportViewFilter.js
frontend/scripts/ResetWordLangFive.sh
frontend/scripts/TestDatabaseSetup.sh
frontend/scripts/TestDatabaseTeardown.sh

The database setup script will now create the TEst/Test directory inside of FV/Workspaces/Data/ if it doesn't exist.
The database teardown script will now delete the TEst/Test directory inside of FV/Workspaces/Data if there are no files or directories left inside of it after the teardown is complete.
Also added some echo lines to make the output more readable.

FW-691 Add functionality to create/delete TEst/Test directory automatically

---

frontend/app/assets/javascripts/models/schemas/options.js
frontend/app/assets/javascripts/views/pages/users/register/index.js

Updated text on the registration page for clarity of who should register.

FW-797 Update text on registration page

---

frontend/app/assets/javascripts/views/components/Dashboard/Statistics/index.js
frontend/app/assets/javascripts/views/components/FVTab/index.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/alphabet/view.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/phrases/view.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/songs-stories/edit.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/songs-stories/entry/view.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/songs-stories/list-view.js
frontend/app/assets/javascripts/views/pages/explore/dialect/media/view.js
frontend/app/assets/javascripts/views/pages/explore/dialect/page-stats.js
frontend/app/assets/javascripts/views/pages/explore/dialect/reports/list-view.js
frontend/app/assets/javascripts/views/themes/FirstVoicesKidsTheme.js
frontend/app/assets/javascripts/views/themes/FirstVoicesTheme.js
frontend/app/assets/javascripts/views/themes/FirstVoicesWorkspaceTheme.js

Created an FVTab component that sets tab styling based on workspace/sections
Statistics: fixed FW-52, fixes really wide pie chart on certain screen widths

FW-851, FW-52

---

frontend/README.md
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/phrases/__cypress__/RecorderCreate-Phrase.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/words/__cypress__/LangAdminViewEdit-Word.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/words/__cypress__/RecorderMediaTrace-Word.js
frontend/package.json

Credit to @coakenfold for a portion of the documentation which was
pulled from Confluence.
Also updated a few Cypress tests for better CI reliability.

FW-944 Cypress test creation/usage documentation in frontend/README.md

---

FirstVoicesEnrichers/src/main/java/ca/firstvoices/nuxeo/utils/EnricherUtils.java
FirstVoicesPublisher/src/main/java/ca/firstvoices/services/UnpublishedChangesServiceImpl.java
FirstVoicesPublisher/src/test/java/ca/firstvoices/operations/CheckUnpublishedChangesTest.java
FirstVoicesPublisher/src/test/java/ca/firstvoices/services/UnpublishedChangesServiceImplTest.java
frontend/app/assets/javascripts/providers/redux/reducers/fvWord/actions.js

Also added call to UnpublishedChanges enricher to fetchword on frontend and a session check to EnricherUtils.

Change UnpublishedChangesService to use methods instead of paths

---

scripts/ci/ReviewerInfoComment.sh
scripts/ci/checkReviewStatus.sh

This pull requests fixes the issue when a pull request reviewer requests changes and then approves the pull request after changes have been made, the action thinks there is still an unapproved review and the transition does not happen.
Duplicate review completed comments being added to issues is also fixed.

FW-1081 Fix Jira transitioning review status check and duplicate comment issue

---

.github/workflows/CypressTests.yml
.github/workflows/build.yml
frontend/README.md
frontend/build.xml

Additionally added Node package caching for build workflow.

FW-1018 Use npm ci instead of npm install for CI workflows

---

docker/README.md
frontend/README.md

Additionally fixed docker run command to persist data on container shutdown.

Update frontend and docker READMEs to have consistent versions

---

.gitignore
docker/.dockerignore
docker/README.md
docker/docker-compose.yml
docker/nuxeo.conf
docker/postgresql.conf

Also updated the docker README.md to explain new usage.

FW-1117 Add Elasticsearch to local docker-compose backend

---

frontend/app/assets/javascripts/views/pages/search/index.js

Removed the with-toggle HOC and related form data/methods
Reorganized component code:
- Moved propTypes annotation to the bottom just above Redux boilerplate
- Moved non-lifecycle methods after render()
- Removed commented out code

FW-917 - Searching in the top navbar then in the filter menu does not update search

---

frontend/app/assets/javascripts/views/AppFrontController.js
frontend/app/assets/javascripts/views/components/FVSnackbar/index.js

This ticket creates a Snackbar for displaying a COVID update. It displays on the front page.

FW-1219: Add FVSnackbar for Physical Distancing update

---

frontend/app/assets/javascripts/views/AppFrontController.js
frontend/app/assets/javascripts/views/components/Browsing/__cypress__/Portal-List-Dialect.js
frontend/app/assets/javascripts/views/components/Browsing/portal-list-dialects.js
frontend/app/assets/javascripts/views/components/Navigation/styles.css

Immersion Switch Hidden & Explore Language Toggle Off By Default

Hide Immersion Switch, Change URL of COVID Banner, & Default Explore Language Toggle Off

---

frontend/app/assets/javascripts/views/components/Editor/AutoSuggestComponent.js
frontend/app/assets/javascripts/views/components/Editor/Preview.js

Autosuggest now correctly shows child and parent categories.
Credit to @coakenfold for the majority of the fix. Thanks Chad!

FW-1293 Fix autosuggest for categories only suggesting parent categories

---

docker/README.md
docker/docker-compose.yml
docker/nuxeo.conf

Additionally modified elasticsearch settings in nuxeo.conf.

FW-1227 Add postgres database to docker

---

frontend/app/assets/javascripts/views/components/DialectFilterList/index.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/words/categories-list-view.js

We plan on fixing this with a backend operation for returning categories, but for now let's take do a FE hack.

FW-1337: Filtering trashed children documents

---

frontend/app/assets/javascripts/views/components/HelperModeToggle/HelperModeToggle.css
frontend/app/assets/javascripts/views/pages/explore/dialect/page-toolbar.js

Hides immersion portal helper mode on dialect page

FW-1344: Temporarily Hide Immersion Portal

---

FirstVoicesPublisher/src/main/java/ca/firstvoices/publisher/listeners/DocumentDeletedUnpublishListener.java
FirstVoicesPublisher/src/main/java/ca/firstvoices/publisher/services/FirstVoicesPublisherService.java
FirstVoicesPublisher/src/main/java/ca/firstvoices/publisher/services/FirstVoicesPublisherServiceImpl.java
FirstVoicesPublisher/src/test/java/ca/firstvoices/listeners/FirstVoicesPublisherTest.java

Code style reformated FirstVoicesPublisherServiceImpl.java. Look at lines 535 and onwards for actual changes. I threw some unit tests in this ticket.

FW-1296: Deletes Categories on Words/Phrases that are Bulk Trashed

---

frontend/app/assets/javascripts/views/components/AlphabetCharacters/AlphabetCharactersData.js
frontend/app/assets/javascripts/views/components/Browsing/DictionaryList.js
frontend/app/assets/javascripts/views/components/SearchDialect/index.js
frontend/app/assets/javascripts/views/pages/explore/dialect/immersion/index.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/phrases/index.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/phrases/phrasesFilteredByCategory.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/words/categoriesDataLayer.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/words/index.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/words/wordsFilteredByCategory.js

https://firstvoices.atlassian.net/browse/FW-1466

FW-1466 Checkboxes on Search Dialect need to be enabled & reset properly

---

frontend/app/assets/javascripts/common/DataSource/useCategories.js
frontend/app/assets/javascripts/common/DataSource/useDocument.js
frontend/app/assets/javascripts/common/DataSource/useListView.js
frontend/app/assets/javascripts/common/DataSource/usePhrases.js
frontend/app/assets/javascripts/common/DataSource/usePortal.js
frontend/app/assets/javascripts/common/DataSource/useProperties.js
frontend/app/assets/javascripts/common/DataSource/useRoute.js
frontend/app/assets/javascripts/common/DataSource/useSearch.js
frontend/app/assets/javascripts/common/DataSource/useSearchDialect.js
frontend/app/assets/javascripts/common/DataSource/useWindowPath.js

Merging in DataSource components from a WIP branch since other developers are using DataSource components and would like to minimize duplication.

Adding dataSource components

---

FirstVoicesOperations/src/main/java/ca/firstvoices/visibility/operations/UpdateVisibilityOperation.java
FirstVoicesOperations/src/main/resources/META-INF/MANIFEST.MF

Forgot to add OSGI-INF/dialect/visibility/visibility-services.xml to manifest file

FW-1594: Add Service Contribution to MANIFEST

---

frontend/app/assets/javascripts/components/Dashboard/Dashboard.css
frontend/app/assets/javascripts/components/Dashboard/DashboardPresentation.js

Changes the current dashboard into one that has 2 columns, which merge if the screen is small.

FW 1613 - Two column dashboard

---

FirstVoicesMaintenance/src/main/java/ca/firstvoices/maintenance/dialect/categories/services/MigrateCategoriesServiceImpl.java

session.getParentDocument() can return null, and subsequent calls on that variable causing NPE.

FW-1715: Fix NPE on session.getParentDocument

---

frontend/app/assets/javascripts/views/components/Breadcrumb/index.js
frontend/app/assets/javascripts/views/components/Browsing/DictionaryListLargeScreen.js
frontend/app/assets/javascripts/views/components/Browsing/flashcard-list.js
frontend/app/assets/javascripts/views/components/Browsing/portal-list-dialects.js
frontend/app/assets/javascripts/views/components/DialectTile/index.js
frontend/app/assets/javascripts/views/components/Navigation/index.js
frontend/app/assets/javascripts/views/pages/debug-typography.js
frontend/app/assets/javascripts/views/pages/explore/dialect/immersion/ImmersionTable/index.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/alphabet/index.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/alphabet/view.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/songs-stories/entry/view.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/songs-stories/list-view.js
frontend/app/assets/javascripts/views/pages/search/index.js
frontend/app/assets/javascripts/views/pages/search/tile.js
frontend/app/assets/stylesheets/main.less

https://firstvoices.atlassian.net/browse/FW-1735

FW-1735 fontAboriginalSans replaced with fontBCSans

---

frontend/app/assets/javascripts/components/DetailWordPhrase/DetailWordPhrasePresentation.js
frontend/app/assets/javascripts/components/DetailWordPhrase/index.js
frontend/app/assets/javascripts/views/pages/explore/dialect/learn/words/view.js

- 'Core component' to be used on the Dashboard Detail page
- In use on Word Detail

DetailWordPhrasePresentation

---

FirstVoicesCoreTests/src/main/java/ca/firstvoices/tests/mocks/services/MockDialectServiceImpl.java
FirstVoicesCoreTests/src/test/java/ca/firstvoices/operations/GenerateDialectTest.java
FirstVoicesCoreTests/src/test/java/ca/firstvoices/operations/GenerateDialectsTest.java
FirstVoicesPublisher/src/main/java/ca/firstvoices/templates/factories/FVDialectFactory.java
frontend/app/assets/javascripts/views/components/Navigation/Login/index.js

- Generate 9 categories in each test dialect, 3 parent 6 child
- Randomly assign words to a category upon creation

FW-1561 Add categories to mock data

---

frontend/app/assets/javascripts/components/DashboardDetail/DashboardDetailPresentation.js

Dashboard Detail: Removed "Show full list view" & "Show detail view" buttons

FW-1837 Drop buttons on Dashboard Detail

---

.gitattributes
FVUserRegistration/src/main/resources/META-INF/MANIFEST.MF
FirstVoicesCoreIO/src/main/java/ca/firstvoices/core/io/marshallers/tasks/SimpleTaskAdapterImpl.java
FirstVoicesCoreIO/src/main/java/ca/firstvoices/core/io/marshallers/tasks/SimpleTaskWriter.java
FirstVoicesCoreIO/src/main/java/ca/firstvoices/core/io/marshallers/tasks/models/SimpleTaskAdapter.java
FirstVoicesOperations/src/main/java/ca/firstvoices/visibility/services/UpdateVisibilityService.java
FirstVoicesOperations/src/main/java/ca/firstvoices/visibility/services/UpdateVisibilityServiceImpl.java
FirstVoicesREST/pom.xml
FirstVoicesREST/src/main/java/org/nuxeo/ecm/restapi/server/jaxrs/firstvoices/SimpleTaskObject.java
FirstVoicesREST/src/test/java/org/nuxeo/ecm/restapi/server/jaxrs/firstvoices/SimpleTaskObjectTest.java
FirstVoicesREST/src/test/resources/OSGI-INF/document-routing-core-types-contrib.xml
FirstVoicesREST/src/test/resources/schemas/route_node.xsd
FirstVoicesRESTPageProviders/UpdateModule.sh
FirstVoicesRESTPageProviders/src/main/resources/META-INF/MANIFEST.MF
FirstVoicesRESTPageProviders/src/main/resources/OSGI-INF/extensions/ca.firstvoices.pageproviders.tasks.xml
FirstVoicesSecurity/src/main/java/ca/firstvoices/securitypolicies/groups/LanguageRecorders.java
FirstVoicesSecurity/src/main/resources/META-INF/MANIFEST.MF
FirstVoicesSecurity/src/main/resources/OSGI-INF/extensions/ca.firstvoices.auth.xml
FirstVoicesSecurity/src/test/java/ca/firstvoices/security/tests/TestSecurityPolicies.java

See postman/ticket for documentation.

FW-1838 - Create new endpoints for simple tasks

---

FirstVoicesCharacters/src/main/java/ca/firstvoices/characters/listeners/AssetListener.java
FirstVoicesCharacters/src/main/java/ca/firstvoices/characters/services/AddConfusablesServiceImpl.java
FirstVoicesCharacters/src/test/java/ca/firstvoices/characters/services/CleanupCharactersServiceImplTest.java
FirstVoicesCoreTests/src/main/resources/META-INF/MANIFEST.MF
FirstVoicesMaintenance/src/main/java/ca/firstvoices/maintenance/listeners/ExecuteRequiredJobsListener.java

A few other small fixes along the way (see commits below).

FW-1875 - Ensure clean confusables does not run automatically after add confusables

---

frontend/app/assets/javascripts/components/WarningBanner/WarningBannerPresentation.js
frontend/app/assets/javascripts/views/hoc/view/with-actions.js
frontend/app/assets/javascripts/views/hoc/view/with-form.js

Handle item being undefined on initial page load after save

Bug-fix-withForm

---

FirstVoicesData/src/main/resources/OSGI-INF/ca.firstvoices.studio.extensions.xml
FirstVoicesData/src/main/resources/data/vocabularies/parts_of_speech.csv
frontend/app/assets/javascripts/views/pages/explore/dialect/create/Word/index.js

Update `parts_of_speech.csv` vocabulary to add `Command` to directory. Also modify the nuxeo studio configuration XML to cause the vocabulary to be recreated on server restart to pick up the new value.

FW-1827 Add "Command" part of speech

---

FirstVoicesData/src/main/resources/OSGI-INF/lifecycle/ca.firstvoices.lifecycle.types.xml
FirstVoicesPublisher/src/main/java/ca/firstvoices/publisher/services/FirstVoicesPublisherServiceImpl.java
FirstVoicesSimplifiedAPI/.gitignore
FirstVoicesSimplifiedAPI/package-lock.json
FirstVoicesSimplifiedAPI/package.json

FW-1967 - use PublisherService for transitioning children

---

frontend/app/common/schemas/options.js
frontend/app/components/SongStoryPages/SongStoryPagesPresentation.js
frontend/app/components/SongsStories/entry/edit.js

Prevent user from seeing html tags in page and form:
- DOMPurify added to SongStoryPagesPresentation translations
- Wysiwyg added to form

FW-1979 html tags rendering in songs/stories

---

.github/pull_request_template.md

- Created the initial checklist for our definition of done to be available on PR

FW-1039 Definition of done PR template

---

frontend/app/components/WordsList/WordsListPresentation.js

Added missing css

---

FirstVoicesREST/src/main/java/org/nuxeo/ecm/restapi/server/jaxrs/firstvoices/SitesObject.java

Logo hotfix

---

.github/workflows/sonar.yml
FirstVoicesREST/src/main/java/org/nuxeo/ecm/restapi/server/jaxrs/firstvoices/SitesObject.java

Update the sonar.yml workflow to address actions version issue

Sonar workflow fix

---

FirstVoicesREST/src/main/java/org/nuxeo/ecm/restapi/server/jaxrs/firstvoices/SitesObject.java

Hotfix 184

---

frontend/app/components/PortalListDialects.js

corrected logo path in JS

---

frontend/app/components/SearchDictionary/SearchDictionaryContainer.js
frontend/app/components/SearchDictionary/SearchDictionaryData.js
frontend/app/components/SearchDictionary/SearchDictionaryPresentation.js

FW-2006 Add decodeURI and location to title

---

modules/common/firstvoices-characters/src/main/java/ca/firstvoices/characters/services/CleanupCharactersServiceImpl.java
modules/common/firstvoices-characters/src/main/java/ca/firstvoices/characters/services/CustomOrderComputeServiceImpl.java
modules/common/firstvoices-characters/src/main/java/ca/firstvoices/characters/workers/CleanConfusablesWorker.java
modules/common/firstvoices-core-tests/src/test/java/ca/firstvoices/testUtil/AbstractTestDataCreatorTest.java
modules/common/firstvoices-maintenance/src/main/java/ca/firstvoices/maintenance/Constants.java
modules/common/firstvoices-maintenance/src/main/java/ca/firstvoices/maintenance/listeners/ExecuteGlobalJobsListener.java
modules/common/firstvoices-maintenance/src/main/resources/OSGI-INF/maintenance/fv-maintenance-contrib.xml
modules/common/firstvoices-maintenance/src/test/java/ca/firstvoices/maintenance/listeners/ExecuteGlobalJobsListenerTest.java
modules/common/firstvoices-publisher/src/test/java/ca/firstvoices/services/PublisherServiceTest.java

FW-2045 - Fix issues with service/workers + global job (new structure)

---

docker/initialsetup.sh

FW-2100 - Provide port as second option for init script

---

docker/UpdatePackage.sh
modules/api/firstvoices-rest-api/src/main/java/org/nuxeo/ecm/restapi/server/jaxrs/firstvoices/LabelsObject.java
modules/api/firstvoices-rest-api/src/main/java/org/nuxeo/ecm/restapi/server/jaxrs/firstvoices/SitesObject.java

Now pull enabled sites from /workspaces in addition to all sites from /sections in explore languages response
Additionally, fix the UpdatePackage.sh script to work with the new module structure and eliminate an error/warning in the Labels endpoint

FW-1309 take 2

---

modules/common/firstvoices-enrichers/src/main/resources/META-INF/MANIFEST.MF

FW-2135 - Correct wrong import for enrichers

---

frontend/.eslintrc
frontend/app/assets/stylesheets/Dialect.less
frontend/app/components/DialectTile.js
frontend/app/components/PortalListDialects.js

FW-1993 FE Private Language Sites on Explore Languages

---

modules/api/firstvoices-rest-api/src/main/java/org/nuxeo/ecm/restapi/server/jaxrs/firstvoices/SitesObject.java

Some small code changes too:
1. no need to rely on fva:dialect when we can get the dialect from the direct parent
2. the correct field for language is fv-dialect:parent_language

FW-2156 - do not attempt to download images guests can't access

---

frontend/app/components/SearchDictionary/SearchDictionaryData.js

Reset pagination on submission of a new search

---

modules/common/firstvoices-enrichers/src/main/java/ca/firstvoices/enrichers/AncestryEnricher.java

Probably a bad sonarlint change (missed the important !)

FW-2170 - Error when sorting words and phrases by letter

---

frontend/app/app.js
frontend/package-lock.json
frontend/package.json
modules/security/firstvoices-security/src/main/java/ca/firstvoices/security/services/FVUserProfileServiceImpl.java
pom.xml

Add sentry support to frontend and backend

---

firstvoices-marketplace/pom.xml
firstvoices-marketplace/src/main/assemble/assembly.xml
pom.xml

modify pom and assembly to activate simplified api by default

---

frontend/app/components/MediaPanels/MediaPanelsPresentation.js

FW-2017 Switch order of media tabs

---

modules/api/firstvoices-rest-api/src/main/java/org/nuxeo/ecm/restapi/server/jaxrs/firstvoices/StatisticsObject.java
modules/api/firstvoices-rest-page-providers/src/main/java/ca/firstvoices/rest/data/Statistics.java

Fix statistics endpoint queries

---

docker/setup.sh

FW-1808 - Marketplace package should be lowercase

---

frontend/app/components/FVLabel/index.js
frontend/app/components/Immersion/Modal/index.js
frontend/app/components/Immersion/Modal/modalContent.js
frontend/app/components/LearnBase/toolbar-navigation.js

FW-2108 FW-2109 immersion bug fixes

---

firstvoices-marketplace/src/main/assemble/assembly.xml

include AWS dependencies in assembly

---

firstvoices-marketplace/src/main/resources/install/templates/first-voices/config/cognito-config.xml.nxftl

remove conditional from cognito template

---

firstvoices-marketplace/src/main/resources/install/templates/first-voices/config/cognito-config.xml.nxftl
modules/security/firstvoices-security-cognito-auth/src/main/java/org/nuxeo/ecm/platform/oauth2/openid/OpenIDConnectProviderRegistryImpl.java

Debugging cognito

---

modules/security/firstvoices-security-cognito-auth/src/main/java/org/nuxeo/ecm/platform/oauth2/openid/OpenIDConnectProviderRegistryImpl.java

update provider on startup

---

frontend/app/common/services/IntlService.js
frontend/app/components/ExploreDialect.js
frontend/app/components/FVLabel/FVLabel.css
frontend/app/components/FVLabel/index.js
frontend/app/components/LearnBase/learning-sidebar.js

FW-2255, FW-2254 - immersion QA fixes

---

modules/security/firstvoices-security-cognito-auth/src/main/java/ca/firstvoices/cognito/AWSAuthenticationServiceFactory.java

Revert commit that broke Cognito

---

.github/workflows/build.yml

update github workflows java version to 11

---

frontend/app/components/DialectTile/DialectTileContainer.js
frontend/app/components/DialectTile/DialectTileData.js
frontend/app/components/DialectTile/DialectTilePresentation.js
frontend/app_v2/package.json

FW-2261 Private language site redirect fix

---

firstvoices-marketplace/pom.xml
modules/api/firstvoices-rest-api-simple/pom.xml
modules/api/firstvoices-rest-api/pom.xml
modules/api/firstvoices-rest-page-providers/pom.xml
modules/api/pom.xml
modules/common/firstvoices-characters/pom.xml
modules/common/firstvoices-core-io/pom.xml
modules/common/firstvoices-core-tests/pom.xml
modules/common/firstvoices-data/pom.xml
modules/common/firstvoices-enrichers/pom.xml
modules/common/firstvoices-export/pom.xml
modules/common/firstvoices-health-monitor/pom.xml
modules/common/firstvoices-maintenance-common/pom.xml
modules/common/firstvoices-maintenance/pom.xml
modules/common/firstvoices-operations/pom.xml
modules/common/firstvoices-publisher/pom.xml
modules/common/pom.xml
modules/features/pom.xml
modules/pom.xml
modules/security/firstvoices-security-cognito-auth/pom.xml
modules/security/firstvoices-security-user-registration/pom.xml
modules/security/firstvoices-security/pom.xml
modules/security/firstvoices-security/src/main/resources/web/nuxeo.war/login.jsp
modules/security/pom.xml
pom.xml

chore: update wording for lockout; update version

---

frontend/app/qa/__cypress__/WordCRUD.js
frontend/cypress/support/commands.js

FW-2274 Add WordCRUD test to cypress

---

frontend/app/components/Media/view.js
frontend/app/components/Preview.js

FW-2091 gifs

---

frontend/app/components/Preview.js
frontend/app/qa/__cypress__/WordCRUD.js
frontend/cypress/support/commands.js

FW-1995 - fix WordCrud tests (and remove waits)

---

frontend/app/components/Phrasebook/copy.js
frontend/app/qa/__cypress__/PhrasebookCreate.js
frontend/app/qa/__cypress__/PhrasebookEdit.js

Cypress: Fix and simplify Phrasebook edit test

---

modules/common/firstvoices-characters/pom.xml
modules/common/firstvoices-characters/src/main/java/ca/firstvoices/characters/listeners/CharacterListener.java
modules/common/firstvoices-characters/src/main/java/ca/firstvoices/characters/operations/ConfusablesStatus.java
modules/common/firstvoices-characters/src/main/resources/OSGI-INF/ca.firstvoices.listeners.xml
modules/common/firstvoices-characters/src/test/java/ca/firstvoices/characters/listeners/CharacterListenerTest.java
modules/common/firstvoices-characters/src/test/java/ca/firstvoices/characters/operations/OperationsTests.java

FW-1995 - Fix character validation; add to confusable status

---

frontend/app/assets/stylesheets/CardView.less
frontend/app/components/Preview.js
frontend/app/components/SongsStories/list-view.js
modules/common/firstvoices-enrichers/src/main/java/ca/firstvoices/enrichers/BookEnricher.java

FW-2093 v2 - Display videos as stories in story grid view

---

frontend/app/assets/stylesheets/CardView.less
frontend/app/components/SongsStories/list-view.js

FW-2093 - Added titles to links for video provides (songs/stories)

---

modules/security/firstvoices-security-cognito-auth/src/main/java/ca/firstvoices/cognito/AWSAwareUserManager.java
modules/security/firstvoices-security-cognito-auth/src/main/resources/OSGI-INF/extensions/ca.firstvoices.cognito.xml
modules/security/firstvoices-security/src/main/resources/web/nuxeo.war/login.jsp

hotfix for cognito lockout issue

---

frontend/app_v2/src/components/ContactUs/ContactUsPresentation.js
frontend/app_v2/src/components/Content/ContentPresentation.js
frontend/app_v2/src/components/DialectHeader/DialectHeaderPresentation.js
frontend/app_v2/src/components/Hero/HeroPresentation.js
frontend/app_v2/src/components/Hero/HeroPresentation.md
frontend/app_v2/src/components/Home/HomePresentation.js
frontend/app_v2/src/components/Topics/TopicsPresentation.js
frontend/app_v2/src/components/Topics/TopicsPresentationTopic.js
frontend/app_v2/src/components/Welcome/WelcomePresentation.js
frontend/app_v2/src/components/WordOfTheDay/WordOfTheDayPresentation.js
frontend/app_v2/tailwind.config.js

FW-2355 styling changes

---

frontend/app/components/SongsStories/index.js

FW-2273 Notify users if a site has no songs/stories

---

frontend/app_v2/webpack/webpack.common.js

Fix build error

---

frontend/app_v2/webpack/webpack.common.js

Small api url fix

---

frontend/app_v2/src/components/AppFrame/AppFrameContainer.js
frontend/app_v2/src/components/DialectHeader/DialectHeaderPresentation.js
frontend/app_v2/webpack/webpack.common.js

Small fix - catch-all properly + save a redirect (FW-2356)

---

modules/api/firstvoices-rest-api/src/main/java/org/nuxeo/ecm/restapi/server/jaxrs/firstvoices/SearchObject.java
modules/api/firstvoices-rest-page-providers/src/main/java/ca/firstvoices/rest/data/SearchResult.java
modules/api/firstvoices-rest-page-providers/src/main/java/ca/firstvoices/rest/data/SearchResults.java

Updates for Guy:
- exactMatch flag
- distinguish stories and songs
- counts of results by type

Updates to Search Endpoint

---

modules/common/firstvoices-operations/src/main/java/ca/firstvoices/operations/bulkupdate/services/BulkUpdateServiceImpl.java

FW-2085 - Save doc after setting prop

---

frontend/app_v2/src/components/Search/SearchPresentation.js
frontend/app_v2/src/components/SearchInput/SearchInputContainer.js
frontend/app_v2/src/components/SearchInput/SearchInputData.js
frontend/app_v2/src/components/SearchInput/SearchInputPresentation.js

FW-2379 - url changes; will need to address the results in DL separately

---

frontend/app/components/withForm/withForm.js

FW-1620 Preserve edits on cancel until confirmation

---

modules/api/firstvoices-rest-api/src/main/java/org/nuxeo/ecm/restapi/server/jaxrs/firstvoices/AlphabetObject.java
modules/api/firstvoices-rest-page-providers/src/main/java/ca/firstvoices/rest/data/Character.java
modules/api/firstvoices-rest-page-providers/src/main/resources/OSGI-INF/extensions/ca.firstvoices.pageproviders.alphabet.xml

Address QA issues for fw-2301

---

frontend/app_v2/src/common/actionHelpers.js
frontend/app_v2/src/common/icons/BackArrow.js
frontend/app_v2/src/common/urlHelpers.js
frontend/app_v2/src/common/useIcon.js
frontend/app_v2/src/components/DictionaryList/DictionaryListPresentation.js
frontend/app_v2/src/components/Search/SearchContainer.js
frontend/app_v2/src/components/Search/SearchData.js
frontend/app_v2/src/components/Search/SearchPresentation.js

FW-2383 search results view fixes and changes v2

---

frontend/app_v2/src/components/Alphabet/AlphabetContainer.js
frontend/app_v2/src/components/Alphabet/AlphabetPresentation.js
frontend/app_v2/src/components/Alphabet/AlphabetPresentationWidget.js
frontend/app_v2/src/components/DictionaryList/DictionaryListPresentation.js
frontend/app_v2/src/components/Hero/HeroPresentation.js
frontend/app_v2/src/components/Home/HomeContainer.js
frontend/app_v2/src/components/Home/HomePresentation.js
frontend/app_v2/src/components/Loading/LoadingContainer.js
frontend/app_v2/src/components/Loading/LoadingPresentation.js
frontend/app_v2/src/components/Loading/index.js
frontend/app_v2/src/components/Search/SearchPresentation.js
frontend/app_v2/tailwind.config.js

FW-2337 Loading component

---

.gitignore
modules/security/firstvoices-security/src/main/resources/OSGI-INF/extensions/ca.firstvoices.cors.xml

fix cors patch

---

modules/common/firstvoices-characters/src/main/java/ca/firstvoices/characters/services/AddConfusablesServiceImpl.java

FW-2386 - check confusables before operating

---

frontend/app_v2/src/components/DictionaryDetail/DictionaryDetailPresentation.js
frontend/app_v2/src/components/Phrase/PhraseContainer.js
frontend/app_v2/src/components/Search/SearchContainer.js
frontend/app_v2/src/components/Search/SearchData.js
frontend/app_v2/src/components/Search/SearchPresentation.js
frontend/app_v2/src/components/Words/WordsContainer.js
frontend/app_v2/src/components/Words/WordsData.js
frontend/app_v2/src/components/Words/WordsPresentation.js

Remove uses of `siteShortUrl` and replace with `useParams` `sitename`

---

frontend/app/common/Helpers.js
frontend/app/components/PageToolbar/PageToolbar.js
frontend/app/components/Word/WordContainer.js
frontend/app/components/Word/WordData.js
frontend/app/components/withForm/withForm.js

** Also changed "Publish Changes" button disable logic so that it is always enabled for FVBooks

FW-2496 stale data

---

docker/UpdateModuleMain.sh
frontend/app/state/reducers/fvBook/actions.js
frontend/app/state/reducers/fvPhrase/actions.js
modules/common/firstvoices-publisher/src/main/java/ca/firstvoices/publisher/services/FirstVoicesPublisherServiceImpl.java
modules/common/firstvoices-publisher/src/main/java/ca/firstvoices/publisher/services/UnpublishedChangesServiceImpl.java

FW-2368 - fix issues with unpublished changes; order of published assets

---

frontend/app/components/Join/JoinData.js
frontend/app/components/Membership/MembershipContainer.js
frontend/app/components/Membership/MembershipData.js
frontend/app/components/Membership/MembershipPresentation.js
frontend/app/state/operations/DirectoryOperations.js
frontend/app/state/reducers/fvCategory/actions.js
modules/common/firstvoices-publisher/src/main/java/ca/firstvoices/publisher/listeners/AutoPublishListener.java
modules/common/firstvoices-publisher/src/main/java/ca/firstvoices/publisher/marshallers/AutoPublishJsonInterceptor.java
modules/common/firstvoices-publisher/src/main/resources/OSGI-INF/extensions/ca.firstvoices.publisher.listeners.xml

+ Fix bug with auto publishing.

FW-2555, FW-1591 - Add snackbar to Membership component

---

firstvoices-marketplace/src/main/resources/install/templates/first-voices/config/fv-elasticsearch-doc-mapping.json
modules/api/firstvoices-rest-api-simple/package-lock.json
modules/api/firstvoices-rest-api/src/main/java/org/nuxeo/ecm/restapi/server/jaxrs/firstvoices/AbstractSearchlikeObject.java
modules/api/firstvoices-rest-api/src/main/java/org/nuxeo/ecm/restapi/server/jaxrs/firstvoices/SongsStoriesObject.java
modules/api/firstvoices-rest-page-providers/src/main/java/ca/firstvoices/rest/data/SearchResult.java
modules/api/firstvoices-rest-page-providers/src/main/java/ca/firstvoices/rest/data/SearchResults.java
modules/common/firstvoices-data/src/main/resources/OSGI-INF/ca.firstvoices.studio.extensions.xml
modules/common/firstvoices-data/src/main/resources/data/schemas/fvaudience.xsd
modules/common/firstvoices-operations/src/main/java/ca/firstvoices/operations/audience/operations/UpdateAudienceOperation.java
modules/common/firstvoices-operations/src/main/resources/META-INF/MANIFEST.MF
modules/common/firstvoices-operations/src/main/resources/OSGI-INF/audience/audience-operations.xml
skaffold/dockerfiles/firstvoices/nuxeo.conf
skaffold/static_k8s_resources/elastic-permanent.yaml

fw-2435-part-2-and-fw-2441

---

docker/nuxeo.conf
modules/api/firstvoices-rest-api-simple/package-lock.json
modules/api/firstvoices-rest-api-simple/src/main/groovy/ca/firstvoices/simpleapi/representations/Site.groovy
modules/api/firstvoices-rest-api-simple/src/main/java/ca/firstvoices/simpleapi/JerseyApplication.java
modules/api/firstvoices-rest-api-simple/src/main/java/ca/firstvoices/simpleapi/endpoints/AuthorizationEndpoint.java
modules/api/firstvoices-rest-api-simple/src/main/java/ca/firstvoices/simpleapi/endpoints/SearchEndpoint.java
modules/api/firstvoices-rest-api-simple/src/main/java/ca/firstvoices/simpleapi/endpoints/SharedEndpoint.java
modules/api/firstvoices-rest-api-simple/src/main/java/ca/firstvoices/simpleapi/endpoints/SiteEndpoint.java
modules/api/firstvoices-rest-api-simple/src/main/java/ca/firstvoices/simpleapi/endpoints/UserEndpoint.java
modules/api/firstvoices-rest-api-simple/src/main/java/ca/firstvoices/simpleapi/endpoints/VocabularyEndpoint.java
modules/api/firstvoices-rest-api-simple/src/main/java/ca/firstvoices/simpleapi/services/FirstVoicesService.java
modules/api/firstvoices-rest-api-simple/src/main/java/ca/firstvoices/simpleapi/services/NuxeoFirstVoicesServiceImplementation.java
modules/api/firstvoices-rest-api-simple/src/main/resources/META-INF/MANIFEST.MF
modules/api/firstvoices-rest-api-simple/src/main/resources/OSGI-INF/extensions/ca.firstvoices.simpleapi.pageproviders.xml
modules/api/firstvoices-rest-api-simple/src/main/resources/OSGI-INF/extensions/ca.firstvoices.simpleapi.requestController.xml
modules/api/firstvoices-rest-api-simple/src/test/java/ca/firstvoices/simpleapi/DirectServiceTest.java
modules/api/firstvoices-rest-api-simple/src/test/java/ca/firstvoices/simpleapi/SimplifiedAPITest.java

FW-337 - simple api modifications

---

firstvoices-marketplace/pom.xml
modules/api/firstvoices-rest-api-simple/pom.xml
modules/api/firstvoices-rest-api/pom.xml
modules/api/firstvoices-rest-page-providers/pom.xml
modules/api/pom.xml
modules/common/firstvoices-characters/pom.xml
modules/common/firstvoices-core-io/pom.xml
modules/common/firstvoices-core-tests/pom.xml
modules/common/firstvoices-data/pom.xml
modules/common/firstvoices-enrichers/pom.xml
modules/common/firstvoices-health-monitor/pom.xml
modules/common/firstvoices-maintenance-common/pom.xml
modules/common/firstvoices-maintenance/pom.xml
modules/common/firstvoices-operations/pom.xml
modules/common/firstvoices-publisher/pom.xml
modules/common/pom.xml
modules/features/pom.xml
modules/pom.xml
modules/security/firstvoices-security-cognito-auth/pom.xml
modules/security/firstvoices-security-user-registration/pom.xml
modules/security/firstvoices-security/pom.xml
modules/security/pom.xml
pom.xml

chore: update version to 3.5.7

---

modules/security/firstvoices-security-user-registration/src/main/java/ca/firstvoices/listeners/FVRegistrationCompletionListener.java
modules/security/firstvoices-security-user-registration/src/main/java/ca/firstvoices/operations/FVRequestToJoinDialectAdminAction.java
modules/security/firstvoices-security-user-registration/src/main/java/ca/firstvoices/utils/FVRegistrationConstants.java
modules/security/firstvoices-security-user-registration/src/main/java/ca/firstvoices/utils/FVRegistrationUtilities.java

FW-2559, FW-2560 - BE preprod fixes

---

modules/common/firstvoices-characters/src/main/java/ca/firstvoices/characters/services/AddConfusablesService.java
modules/common/firstvoices-characters/src/main/java/ca/firstvoices/characters/services/AddConfusablesServiceImpl.java
modules/common/firstvoices-characters/src/test/java/ca/firstvoices/characters/services/AddConfusablesServiceImplTest.java

FW-2386 - add confusables from other sites fixes

---

frontend/app/components/Games/parachute/index.js
frontend/app/components/Games/wordsearch/index.js
modules/common/firstvoices-characters/src/main/java/ca/firstvoices/characters/operations/ComputeCustomOrder.java
modules/common/firstvoices-characters/src/main/java/ca/firstvoices/characters/services/CustomOrderComputeServiceImpl.java

In addition, added a new variation to the CustomOrderRecompute end-point to handle alphabets.

FW-2569 - word search / parachute game changes

---

modules/common/firstvoices-core-io/src/main/java/ca/firstvoices/core/io/listeners/OverwriteAuditEventListener.java
modules/common/firstvoices-operations/src/main/java/ca/firstvoices/operations/bulkupdate/services/BulkUpdateServiceImpl.java

FW-2572, FW-2574 exclude search for audit log; fix bulk operations issue

---

firstvoices-marketplace/pom.xml
modules/api/firstvoices-rest-api-simple/pom.xml
modules/api/firstvoices-rest-api/pom.xml
modules/api/firstvoices-rest-page-providers/pom.xml
modules/api/pom.xml
modules/common/firstvoices-characters/pom.xml
modules/common/firstvoices-core-io/pom.xml
modules/common/firstvoices-core-tests/pom.xml
modules/common/firstvoices-data/pom.xml
modules/common/firstvoices-enrichers/pom.xml
modules/common/firstvoices-health-monitor/pom.xml
modules/common/firstvoices-maintenance-common/pom.xml
modules/common/firstvoices-maintenance/pom.xml
modules/common/firstvoices-maintenance/src/main/java/ca/firstvoices/maintenance/listeners/ExecuteGlobalJobsListener.java
modules/common/firstvoices-operations/pom.xml
modules/common/firstvoices-publisher/pom.xml
modules/common/firstvoices-publisher/src/main/java/ca/firstvoices/publisher/listeners/AutoPublishListener.java
modules/common/pom.xml
modules/features/pom.xml
modules/pom.xml
modules/security/firstvoices-security-cognito-auth/pom.xml
modules/security/firstvoices-security-user-registration/pom.xml
modules/security/firstvoices-security/pom.xml
modules/security/pom.xml
pom.xml

Prerelease 3.5.8

---

docker/UpdateModuleMain.sh
docker/nuxeo.conf
modules/api/firstvoices-rest-api-simple/src/main/groovy/ca/firstvoices/simpleapi/representations/traits/Translatable.groovy
modules/api/firstvoices-rest-api-simple/src/main/java/ca/firstvoices/simpleapi/SimpleAPIServlet.java
modules/api/firstvoices-rest-api-simple/src/main/java/ca/firstvoices/simpleapi/nuxeo/SimpleAPINuxeoConfiguration.java
modules/api/firstvoices-rest-api-simple/src/main/java/ca/firstvoices/simpleapi/nuxeo/SimpleAPINuxeoConfigurationDescriptorImpl.java
modules/api/firstvoices-rest-api-simple/src/main/java/ca/firstvoices/simpleapi/security/EarlyAccessFilter.java
modules/api/firstvoices-rest-api-simple/src/main/resources/OSGI-INF/extensions/ca.firstvoices.simpleapi.config.xml

SimpleAPI: limit api to only allowed sites (if set)

---

modules/common/firstvoices-operations/src/main/java/ca/firstvoices/operations/audiofix/AudioFixOperation.java
modules/common/firstvoices-operations/src/main/resources/META-INF/MANIFEST.MF
modules/common/firstvoices-operations/src/main/resources/OSGI-INF/audiofix/audiofix-operations.xml
pom.xml
skaffold/charts/firstvoices/templates/k8s-firstvoices.deployment.yaml
skaffold/charts/firstvoices/values.yaml
skaffold/dockerfiles/firstvoices/nuxeo.conf
skaffold/skaffold.yaml
skaffold/static_k8s_resources/elastic-permanent.yaml
skaffold/static_k8s_resources/m2-cache-pvc.yaml

Acl fix operation

---

modules/common/firstvoices-enrichers/src/main/java/ca/firstvoices/enrichers/utils/EnricherUtils.java

FW-2600 - pull speaker Ids from proxy field

---

.github/workflows/eks-deploy.yml

Assume role ARN

---

.github/workflows/eks-deploy.yml
skaffold/aws-transient.env

Install IAM Binary

---

firstvoices-marketplace/src/main/resources/install/templates/first-voices/config/fv-elasticsearch-doc-mapping.json
modules/api/firstvoices-rest-api/src/main/java/org/nuxeo/ecm/restapi/server/jaxrs/firstvoices/AbstractSearchlikeObject.java
modules/api/firstvoices-rest-api/src/main/java/org/nuxeo/ecm/restapi/server/jaxrs/firstvoices/SongsStoriesObject.java
modules/api/firstvoices-rest-page-providers/src/main/java/ca/firstvoices/rest/data/BookSearchResult.java
modules/api/firstvoices-rest-page-providers/src/main/java/ca/firstvoices/rest/data/SearchResult.java
skaffold/base.env
skaffold/charts/firstvoices/templates/elastic.deploy.yaml
skaffold/skaffold.build.kaniko.yaml

fix songs and stories

---

frontend/app_v2/src/components/Categories/CategoriesData.js
frontend/app_v2/src/components/Category/CategoryData.js
frontend/app_v2/src/components/Dictionary/DictionaryData.js
frontend/app_v2/src/components/DictionaryList/DictionaryListPresentation.js
modules/api/firstvoices-rest-api/src/main/java/org/nuxeo/ecm/restapi/server/jaxrs/firstvoices/AbstractSearchlikeObject.java
modules/api/firstvoices-rest-api/src/main/java/org/nuxeo/ecm/restapi/server/jaxrs/firstvoices/DictionaryObject.java
modules/api/firstvoices-rest-page-providers/src/main/java/ca/firstvoices/rest/data/Category.java

Update param names
